spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'

  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://root:MlNRoFUlnU7PQbNcDuNj4Yb7Ujvt3mz8@lk5ax5.stackhero-network.com/root?useSSL=true&requireSSL=true
#    username: root
#    password: MlNRoFUlnU7PQbNcDuNj4Yb7Ujvt3mz8
    url: jdbc:mysql://localhost:3306/epicbyte_database?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password:
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    epic-byte: ${EMAIL:}
#    username: ${EMAIL:}
#    password: ${EMAIL_PASSWORD:}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
      springframework:
        security: DEBUG
server:
  port: ${PORT:5000}
admin:
  username: ${ADMIN_USERNAME:admin}
  password: ${ADMIN_PASSWORD:admin}