spring:
  jpa:
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/epicbyte_database?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
#    username: root
#    password:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgres://u17hrqpe6rt51v:p4ea6092c0879d7721875a6211945a7d4cfcee2e96ecf47b43e99b35c99eb1daf@c9tiftt16dc3eo.cluster-czz5s0kz4scl.eu-west-1.rds.amazonaws.com:5432/dbbnq9vvedonp9
    username: u17hrqpe6rt51v
    password: p4ea6092c0879d7721875a6211945a7d4cfcee2e96ecf47b43e99b35c99eb1daf

logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
      springframework:
        security: DEBUG

server:
  port: ${PORT:5000}
admin:
  username: ${ADMIN_USERNAME:admin}
  password: ${ADMIN_PASSWORD:admin}