services:
  db:
    image: mysql
    ports:
      - "3307:3306"
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin']
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
  epicbyte:
    depends_on:
      - db
    image: pepetrov96/epicbyte:v1
    ports:
      - "5000:5000"
    environment:
        - MYSQL_HOST=db
        - MYSQL_PORT=3307
        - MYSQL_USER=root
        - MYSQL_PASSWORD=
        - API_BASE_URL=http://localhost:5000
  epicbyte-api:
    depends_on:
      - db
    image: pepetrov96/epicbyte-api:v1
    ports:
      - "5001:5001"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3307
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - API_BASE_URL=http://localhost:5001