services:
  EpicByte:
    container_name: epic-byte
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=epic_byte
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes